# Generated by Django 4.2.4 on 2023-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(upload_to="posts"),
        ),
    ]
