# Generated by Django 4.2.4 on 2023-10-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_tags_particpations_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_proof",
            field=models.FileField(default=1, upload_to="Proofs"),
        ),
    ]
